version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: msn-weather-app
    ports:
      - "8080:80"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
